services:
  # 1. Grafana Alloy (The Collector)
  # Receives Faro data and forwards it to Loki and Tempo
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12347:12347" # Port for Faro Web SDK to send data
      - "12345:12345" # Internal debugging
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  # 2. Loki (Logs Database)
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # 3. Tempo (Traces Database)
  tempo:
    image: grafana/tempo:2.4.1
    ports:
      - "3200:3200" # Tempo HTTP
      - "4317:4317" # OTLP GRPC
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yml:/etc/tempo.yaml

  # 4. Grafana (Dashboard)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  # 5. React App (Faro Test UI)
  react-app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - HOST=0.0.0.0
      - PORT=3002
    depends_on:
      - alloy

volumes:
  grafana-storage:
